#!/bin/bash

rm -f Tserial.dat

date 
pwd; echo

echo "-------------------------"
echo " Mandel runs 10 times    "
echo "-------------------------"

make mandel; echo
for i in {1..10}; do ./mandel >> Tserial.dat; done

echo Best Tserial out of 10 :; echo 
cat Tserial.dat | sort -n | head -1; echo
echo done
